// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZta5sWToQu0k4WWE8pzJlv5sSgCnSwH8',
    appId: '1:775272834629:web:725b47e97816d3e3abe52c',
    messagingSenderId: '775272834629',
    projectId: 'akcars-878ad',
    authDomain: 'akcars-878ad.firebaseapp.com',
    storageBucket: 'akcars-878ad.firebasestorage.app',
    measurementId: 'G-5XE5TTR1P5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq-K3A9mOznhil6AX4PYWJzIsYZ_UnWrU',
    appId: '1:775272834629:android:f1a93ff6f6b174b8abe52c',
    messagingSenderId: '775272834629',
    projectId: 'akcars-878ad',
    storageBucket: 'akcars-878ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhhGhahmrz5qJvaS-9jKv7HO9RwmnwqE',
    appId: '1:775272834629:ios:0540d1fbe46c9bb1abe52c',
    messagingSenderId: '775272834629',
    projectId: 'akcars-878ad',
    storageBucket: 'akcars-878ad.firebasestorage.app',
    iosBundleId: 'om.akcars.app',
  );
}
